# Generated by Django 3.0.5 on 2020-04-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('rol', models.IntegerField(choices=[(1, 'admin'), (2, 'dueño'), (3, 'evaluador')])),
                ('rut', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=35)),
            ],
        ),
    ]
