# Generated by Django 3.0.5 on 2020-04-12 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='credits_history',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('time_recharge', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
