# Generated by Django 3.0.5 on 2020-04-12 05:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_social_networks_subscription_plan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('Number', models.CharField(max_length=12)),
                ('advertisement_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('advertisement_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.advertisement')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
