# Generated by Django 3.0.5 on 2020-04-21 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
        ('home', '0005_auto_20200412_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='credits_history',
        ),
        migrations.RenameField(
            model_name='credits',
            old_name='current_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='credits',
            name='days',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='advertisement_id',
        ),
        migrations.RemoveField(
            model_name='social_networks',
            name='advertisement_id',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='Social_network',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.social_networks'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='credits_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.credits'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='open_from',
            field=models.IntegerField(choices=[(1, '00:00'), (2, '00:30'), (3, '01:00'), (4, '01:30'), (5, '02:00'), (6, '02:30'), (7, '03:00'), (8, '03:30'), (9, '04:00'), (10, '04:30'), (11, '05:00'), (12, '05:30'), (13, '06:00'), (14, '06:30'), (15, '07:00'), (16, '07:30'), (17, '08:00'), (18, '08:30'), (19, '09:00'), (20, '09:30'), (21, '10:00'), (22, '10:30'), (23, '11:00'), (24, '11:30'), (25, '12:00'), (26, '12:30'), (27, '13:00'), (28, '13:30'), (29, '14:00'), (30, '14:30'), (31, '15:00'), (32, '15:30'), (31, '16:00'), (32, '16:30'), (19, '17:00'), (20, '17:30'), (21, '18:00'), (22, '18:30'), (23, '19:00'), (24, '19:30'), (25, '20:00'), (26, '20:30'), (27, '21:00'), (28, '21:30'), (29, '22:00'), (30, '22:30'), (31, '23:00'), (32, '23:30')], default=None),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='open_to',
            field=models.IntegerField(choices=[(1, '00:00'), (2, '00:30'), (3, '01:00'), (4, '01:30'), (5, '02:00'), (6, '02:30'), (7, '03:00'), (8, '03:30'), (9, '04:00'), (10, '04:30'), (11, '05:00'), (12, '05:30'), (13, '06:00'), (14, '06:30'), (15, '07:00'), (16, '07:30'), (17, '08:00'), (18, '08:30'), (19, '09:00'), (20, '09:30'), (21, '10:00'), (22, '10:30'), (23, '11:00'), (24, '11:30'), (25, '12:00'), (26, '12:30'), (27, '13:00'), (28, '13:30'), (29, '14:00'), (30, '14:30'), (31, '15:00'), (32, '15:30'), (31, '16:00'), (32, '16:30'), (19, '17:00'), (20, '17:30'), (21, '18:00'), (22, '18:30'), (23, '19:00'), (24, '19:30'), (25, '20:00'), (26, '20:30'), (27, '21:00'), (28, '21:30'), (29, '22:00'), (30, '22:30'), (31, '23:00'), (32, '23:30')], default=None),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='phones',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.phones'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='evaluate.Ratings'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='subscription_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.subscription_plan'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='url_website',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='credits',
            name='time_recharge',
            field=models.TimeField(default=None),
        ),
        migrations.DeleteModel(
            name='type',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='Type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.typeA'),
        ),
    ]
