# Generated by Django 3.0.5 on 2020-04-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200424_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='Social_network',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='Social_network',
            field=models.ManyToManyField(default=None, to='home.social_networks'),
        ),
    ]
