# Generated by Django 3.0.5 on 2020-04-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200424_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='phones',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='phones',
            field=models.ManyToManyField(default=None, to='home.phones'),
        ),
    ]
