# Generated by Django 3.0.5 on 2020-04-24 22:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200424_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameSocialNetworks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_socialNetwork', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='social_networks',
            name='user_socialNetwork',
        ),
        migrations.AddField(
            model_name='social_networks',
            name='red',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.NameSocialNetworks'),
        ),
    ]
