# Generated by Django 3.0.5 on 2020-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200425_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_networks',
            name='red',
        ),
        migrations.AddField(
            model_name='social_networks',
            name='red',
            field=models.ManyToManyField(default=None, to='home.NameSocialNetworks'),
        ),
    ]
