# Generated by Django 3.0.5 on 2020-04-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_advertisement_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='incorporation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='latitude_longitude',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
