# Generated by Django 3.0.5 on 2020-04-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200426_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='show_adress',
            field=models.BooleanField(default=False),
        ),
    ]
