# Generated by Django 3.0.5 on 2020-04-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_advertisement_show_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='show_phones',
            field=models.BooleanField(default=False),
        ),
    ]
