# Generated by Django 3.0.5 on 2020-04-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_advertisement_show_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=None, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='logo',
            field=models.ImageField(default=None, upload_to='static/img/logo'),
        ),
    ]
