# Generated by Django 3.0.5 on 2020-04-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200427_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='price_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price_to',
            field=models.IntegerField(default=0),
        ),
    ]
