# Generated by Django 3.0.5 on 2020-04-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_openinghours_specialdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='open_from',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='open_to',
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekday_from',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], unique=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekday_to',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')]),
        ),
    ]
